############################
# --- Required options --- #
############################
title: "Ben Tamam"
description: "Senior Offensive Security Engineer focused on Red Teaming, Active Directory & Cloud Identity research, and EDR evasion."
author: "Ben Tamam"
lang: en
timezone: "Asia/Jerusalem"

###############################################
# --- Navigation bar --- #
###############################################
navbar-links:
  About Me: "aboutme"   # /aboutme
  Blog: "/"             # homepage lists all posts

################
# --- Logo --- #
################
avatar: "/assets/img/avatar-icon.png"
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################
social-network-links:
  linkedin: bentamam
  github: BenTamam
rss-description: "Security research & red teaming portfolio — Windows internals, AD/Entra ID, detection engineering, and EDR bypasses."

###########################
# --- General options --- #
###########################
share-links-active:
  linkedin: true
  twitter: false

# canonical pretty URL (also set `url` to enable absolute OG/Twitter links)
url: "https://bentamam.github.io"
url-pretty: "bentamam.github.io"

title-on-all-pages: true
excerpt_length: 40
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: false
navbar-var-length: true

# Keywords: tuned to identity research/detection engineering
keywords: "Ben Tamam, security researcher, offensive security, red team, Active Directory, Entra ID, cloud identity, Windows internals, detection engineering, EDR evasion, malware development, Python"

######################################
# --- Colours / background image --- #
######################################
page-col: "#ffffff"
text-col: "#1e293b"
link-col: "#0ea5e9"
hover-col: "#0284c7"
navbar-col: "#0f172a"
navbar-text-col: "#f1f5f9"
navbar-border-col: "#1e293b"
footer-col: "#0f172a"
footer-text-col: "#94a3b8"
footer-link-col: "#f1f5f9"
footer-hover-col: "#38bdf8"

#################################
# --- Web Analytics Section --- #
#################################
# gtag: "G-XXXXXXXXXX"   # add if you want GA4

################
# --- Misc --- #
################
date_format: "%B %-d, %Y"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/

# remove paginate warning since homepage is index.md
paginate: # (unset)

kramdown:
  input: GFM

# Site-wide defaults
defaults:
  - scope: { path: "", type: "posts" }
    values:
      layout: "post"
      comments: false
      social-share: true
      # fallback share image for social cards (create this file)
      share-img: "/assets/img/og/site-card.png"
  - scope: { path: "" }
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-sitemap   # keep sitemap for SEO
  # - jekyll-paginate  # leave disabled unless you use index.html with paginate
